name: Sync to Hugging Face Space

on:
  push:
    branches: [ "hf-deploy" ]   # runs only when master changes
  workflow_dispatch:

jobs:
  push_to_hf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master         # ensure we checkout master
          fetch-depth: 0

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: ritup3
          SPACE_NAME: PersonaRag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git remote remove space 2>/dev/null || true
          git remote add space https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$SPACE_NAME

          # master -> HF main
          git push space HEAD:main --force
